default['apache']['LoadModule'] = [
  "authn_file_module lib64/httpd/modules/mod_authn_file.so",
#  "authn_dbm_module lib64/httpd/modules/mod_authn_dbm.so",
#  "authn_anon_module lib64/httpd/modules/mod_authn_anon.so",
#  "authn_dbd_module lib64/httpd/modules/mod_authn_dbd.so",
#  "authn_socache_module lib64/httpd/modules/mod_authn_socache.so",
  "authn_core_module lib64/httpd/modules/mod_authn_core.so",
  "authz_host_module lib64/httpd/modules/mod_authz_host.so",
  "authz_groupfile_module lib64/httpd/modules/mod_authz_groupfile.so",
  "authz_user_module lib64/httpd/modules/mod_authz_user.so",
#  "authz_dbm_module lib64/httpd/modules/mod_authz_dbm.so",
#  "authz_owner_module lib64/httpd/modules/mod_authz_owner.so",
#  "authz_dbd_module lib64/httpd/modules/mod_authz_dbd.so",
  "authz_core_module lib64/httpd/modules/mod_authz_core.so",
#  "authnz_ldap_module lib64/httpd/modules/mod_authnz_ldap.so",
  "access_compat_module lib64/httpd/modules/mod_access_compat.so",
  "auth_basic_module lib64/httpd/modules/mod_auth_basic.so",
#  "auth_form_module lib64/httpd/modules/mod_auth_form.so",
#  "auth_digest_module lib64/httpd/modules/mod_auth_digest.so",
#  "allowmethods_module lib64/httpd/modules/mod_allowmethods.so",
#  "file_cache_module lib64/httpd/modules/mod_file_cache.so",
#  "cache_module lib64/httpd/modules/mod_cache.so",
#  "cache_disk_module lib64/httpd/modules/mod_cache_disk.so",
#  "cache_socache_module lib64/httpd/modules/mod_cache_socache.so",
  "socache_shmcb_module lib64/httpd/modules/mod_socache_shmcb.so",
#  "socache_dbm_module lib64/httpd/modules/mod_socache_dbm.so",
  "socache_memcache_module lib64/httpd/modules/mod_socache_memcache.so",
#  "socache_dc_module lib64/httpd/modules/mod_socache_dc.so",
#  "watchdog_module lib64/httpd/modules/mod_watchdog.so",
#  "macro_module lib64/httpd/modules/mod_macro.so",
#  "dbd_module lib64/httpd/modules/mod_dbd.so",
#  "bucketeer_module lib64/httpd/modules/mod_bucketeer.so",
#  "dumpio_module lib64/httpd/modules/mod_dumpio.so",
#  "echo_module lib64/httpd/modules/mod_echo.so",
#  "case_filter_module lib64/httpd/modules/mod_case_filter.so",
#  "case_filter_in_module lib64/httpd/modules/mod_case_filter_in.so",
#  "buffer_module lib64/httpd/modules/mod_buffer.so",
#  "data_module lib64/httpd/modules/mod_data.so",
#  "ratelimit_module lib64/httpd/modules/mod_ratelimit.so",
  "reqtimeout_module lib64/httpd/modules/mod_reqtimeout.so",
#  "ext_filter_module lib64/httpd/modules/mod_ext_filter.so",
#  "request_module lib64/httpd/modules/mod_request.so",
#  "include_module lib64/httpd/modules/mod_include.so",
  "filter_module lib64/httpd/modules/mod_filter.so",
#  "reflector_module lib64/httpd/modules/mod_reflector.so",
#  "substitute_module lib64/httpd/modules/mod_substitute.so",
#  "sed_module lib64/httpd/modules/mod_sed.so",
#  "charset_lite_module lib64/httpd/modules/mod_charset_lite.so",
#  "deflate_module lib64/httpd/modules/mod_deflate.so",
#  "xml2enc_module lib64/httpd/modules/mod_xml2enc.so",
#  "proxy_html_module lib64/httpd/modules/mod_proxy_html.so",
  "mime_module lib64/httpd/modules/mod_mime.so",
#  "ldap_module lib64/httpd/modules/mod_ldap.so",
  "log_config_module lib64/httpd/modules/mod_log_config.so",
#  "log_debug_module lib64/httpd/modules/mod_log_debug.so",
#  "log_forensic_module lib64/httpd/modules/mod_log_forensic.so",
#  "logio_module lib64/httpd/modules/mod_logio.so",
#  "lua_module lib64/httpd/modules/mod_lua.so",
  "env_module lib64/httpd/modules/mod_env.so",
#  "mime_magic_module lib64/httpd/modules/mod_mime_magic.so",
#  "expires_module lib64/httpd/modules/mod_expires.so",
  "headers_module lib64/httpd/modules/mod_headers.so",
#  "usertrack_module lib64/httpd/modules/mod_usertrack.so",
#  "unique_id_module lib64/httpd/modules/mod_unique_id.so",
  "setenvif_module lib64/httpd/modules/mod_setenvif.so",
  "version_module lib64/httpd/modules/mod_version.so",
#  "remoteip_module lib64/httpd/modules/mod_remoteip.so",
  "proxy_module lib64/httpd/modules/mod_proxy.so",
#  "proxy_connect_module lib64/httpd/modules/mod_proxy_connect.so",
#  "proxy_ftp_module lib64/httpd/modules/mod_proxy_ftp.so",
  "proxy_http_module lib64/httpd/modules/mod_proxy_http.so",
#  "proxy_fcgi_module lib64/httpd/modules/mod_proxy_fcgi.so",
#  "proxy_scgi_module lib64/httpd/modules/mod_proxy_scgi.so",
#  "proxy_fdpass_module lib64/httpd/modules/mod_proxy_fdpass.so",
#  "proxy_wstunnel_module lib64/httpd/modules/mod_proxy_wstunnel.so",
#  "proxy_ajp_module lib64/httpd/modules/mod_proxy_ajp.so",
#  "proxy_balancer_module lib64/httpd/modules/mod_proxy_balancer.so",
#  "proxy_express_module lib64/httpd/modules/mod_proxy_express.so",
#  "session_module lib64/httpd/modules/mod_session.so",
#  "session_cookie_module lib64/httpd/modules/mod_session_cookie.so",
#  "session_crypto_module lib64/httpd/modules/mod_session_crypto.so",
#  "session_dbd_module lib64/httpd/modules/mod_session_dbd.so",
#  "slotmem_shm_module lib64/httpd/modules/mod_slotmem_shm.so",
#  "slotmem_plain_module lib64/httpd/modules/mod_slotmem_plain.",so
  "ssl_module lib64/httpd/modules/mod_ssl.so",
#  "dialup_module lib64/httpd/modules/mod_dialup.so",
#  "lbmethod_byrequests_module lib64/httpd/modules/mod_lbmethod_byrequests.so",
#  "lbmethod_bytraffic_module lib64/httpd/modules/mod_lbmethod_bytraffic.so",
#  "lbmethod_bybusyness_module lib64/httpd/modules/mod_lbmethod_bybusyness.so",
#  "lbmethod_heartbeat_module lib64/httpd/modules/mod_lbmethod_heartbeat.so",
  "mpm_event_module lib64/httpd/modules/mod_mpm_event.so",
  "unixd_module lib64/httpd/modules/mod_unixd.so",
#  "heartbeat_module lib64/httpd/modules/mod_heartbeat.so",
#  "heartmonitor_module lib64/httpd/modules/mod_heartmonitor.so",
#  "dav_module lib64/httpd/modules/mod_dav.so",
  "status_module lib64/httpd/modules/mod_status.so",
  "autoindex_module lib64/httpd/modules/mod_autoindex.so",
#  "asis_module lib64/httpd/modules/mod_asis.so",
#  "info_module lib64/httpd/modules/mod_info.so",
#  "suexec_module lib64/httpd/modules/mod_suexec.so",
#  "cgid_module lib64/httpd/modules/mod_cgid.so",
#  "dav_fs_module lib64/httpd/modules/mod_dav_fs.so",
#  "dav_lock_module lib64/httpd/modules/mod_dav_lock.so",
#  "vhost_alias_module lib64/httpd/modules/mod_vhost_alias.so",
#  "negotiation_module lib64/httpd/modules/mod_negotiation.so",
  "dir_module lib64/httpd/modules/mod_dir.so",
#  "actions_module lib64/httpd/modules/mod_actions.so",
#  "speling_module lib64/httpd/modules/mod_speling.so",
#  "userdir_module lib64/httpd/modules/mod_userdir.so",
  "alias_module lib64/httpd/modules/mod_alias.so",
  "rewrite_module lib64/httpd/modules/mod_rewrite.so",
]

